language: go

services:
  - docker

go:
  - 1.11.x
os:
  - linux
env:
  - GO111MODULE=on

jobs:
  include:
    - stage: test
      install:
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.16.0
      script:
        - go test ./...
        - ./bin/golangci-lint run ./...
    - stage: build
      install: skip
      before_script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      script:
        - VERSION=$(git rev-parse --short HEAD)
        - docker build . -t "maxormo/cluster-monitor:${VERSION}" -t maxormo/cluster-monitor:latest
        - docker push maxormo/cluster-monitor


stages:
  - name: test
  - name: build
    if: branch = master and not type = pull_request